version: '3'
services:
  ds-notebook:
    build:
      context: ./jupyter/auxiliary/
      dockerfile: Dockerfile
    volumes:
      - "./jupyter/:/home/jovyan/work"
    ports:
      - 8888:8888
    user: root
    container_name: "jupyter_notebook"
    environment:
      AWS_ENDPOINT_URL: ${AWS_ENDPOINT_URL}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      INPUT_FILE_PATTERN: ${INPUT_FILE_PATTERN}
      OUTPUT_FILE_PATTERN: ${OUTPUT_FILE_PATTERN}
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"
  
  localstack:
    image: localstack/localstack
    ports:
      - 4566:4566
    container_name: "s3_localstack"
    environment:
      SERVICES: s3

  aws-cli:
    image: amazon/aws-cli
    container_name: "aws_cli"
    environment:
      AWS_ENDPOINT_URL: ${AWS_ENDPOINT_URL}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    entrypoint: tail -f /dev/null

volumes:
  postgres_data:
    driver: local